# Generated by Django 4.2.28 on 2026-03-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='demand',
            field=models.DurationField(verbose_name='Betreuungsbedarf pro Woche'),
        ),
    ]
