# Generated by Django 5.2.12 on 2026-03-25 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_poolagreement_payer'),
        ('pedagogy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolSchoolAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_rate', models.DecimalField(decimal_places=2, help_text='Pauschalentgelt in Euro pro betreutem Fall', max_digits=8, verbose_name='Pauschalentgelt pro Fall')),
                ('max_supervisions', models.PositiveIntegerField(help_text='Anzahl der aktuell erlaubten Betreuungen laut Vereinbarung', verbose_name='Max. Betreuungen')),
                ('start', models.DateField(verbose_name='Beginn')),
                ('end', models.DateField(verbose_name='Ende')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_school_agreements', to='finance.costpayer', verbose_name='Kostenzahler')),
            ],
            options={
                'verbose_name': 'Poolschulen-Vereinbarung',
                'verbose_name_plural': 'Poolschulen-Vereinbarungen',
                'ordering': ['-start'],
            },
        ),
    ]
