# Generated by Django 5.2.12 on 2026-03-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_costpayer_options_alter_feeagreement_options_and_more'),
        ('hr', '0003_alter_absence_options_alter_applicant_options_and_more'),
        ('pedagogy', '0002_poolschoolagreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-start'], 'verbose_name': 'Antrag', 'verbose_name_plural': 'Anträge'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_name'], 'verbose_name': 'Schule', 'verbose_name_plural': 'Schulen'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Schulkind', 'verbose_name_plural': 'Schulkinder'},
        ),
        migrations.AlterModelOptions(
            name='supervision',
            options={'ordering': ['-start'], 'verbose_name': 'Betreuung', 'verbose_name_plural': 'Betreuungen'},
        ),
        migrations.AlterField(
            model_name='request',
            name='demand',
            field=models.DurationField(help_text='Genehmigter wöchentlicher Betreuungsumfang', verbose_name='Betreuungsbedarf pro Woche'),
        ),
        migrations.AlterField(
            model_name='request',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='pedagogy.school', verbose_name='Schule'),
        ),
        migrations.AlterField(
            model_name='request',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='pedagogy.student', verbose_name='Schulkind'),
        ),
        migrations.AlterField(
            model_name='request',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Ende der Bewilligungsperiode. Leer lassen, wenn unbefristet.', null=True, verbose_name='Gültig bis'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='finance.costpayer', verbose_name='Kostenzahler'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisions', to='hr.employee', verbose_name='Betreuer:in'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisions', to='pedagogy.school', verbose_name='Schule'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='school_days',
            field=models.PositiveIntegerField(help_text='Anzahl der Schultage im Betreuungszeitraum', verbose_name='Schultage'),
        ),
        migrations.AddConstraint(
            model_name='poolschoolagreement',
            constraint=models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='poolschoolagreement_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('start')), _connector='OR'), name='request_valid_to_after_start'),
        ),
        migrations.AddConstraint(
            model_name='supervision',
            constraint=models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='supervision_end_after_start'),
        ),
    ]
