# Generated by Django 5.2.12 on 2026-03-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0003_rename_school_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-start_date'], 'verbose_name': 'Antrag', 'verbose_name_plural': 'Anträge'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'Schule', 'verbose_name_plural': 'Schulen'},
        ),
        migrations.AlterModelOptions(
            name='supervision',
            options={'ordering': ['-start_date'], 'verbose_name': 'Betreuung', 'verbose_name_plural': 'Betreuungen'},
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Beginn'),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('in_coordination', 'In Abstimmung'), ('rejected', 'Abgelehnt'), ('approved', 'Genehmigt')], db_index=True, default='draft', max_length=50, verbose_name='Zustand'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Beginn'),
        ),
    ]
