# Generated by Django 5.2.12 on 2026-03-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0007_db_index_to_meta_indexes"),
        ("pedagogy", "0004_add_db_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="start_date",
            field=models.DateField(verbose_name="Beginn"),
        ),
        migrations.AlterField(
            model_name="request",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("in_coordination", "In Abstimmung"),
                    ("rejected", "Abgelehnt"),
                    ("approved", "Genehmigt"),
                ],
                default="draft",
                max_length=50,
                verbose_name="Zustand",
            ),
        ),
        migrations.AlterField(
            model_name="supervision",
            name="start_date",
            field=models.DateField(verbose_name="Beginn"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["start_date"], name="request_start_date_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["state"], name="request_state_idx"),
        ),
        migrations.AddIndex(
            model_name="supervision",
            index=models.Index(
                fields=["start_date"], name="supervision_start_date_idx"
            ),
        ),
    ]
