# Generated by Django 5.2.12 on 2026-04-01 21:40

from django.db import migrations, models


def fix_existing_tandem_prophylactic(apps, schema_editor):
    Supervision = apps.get_model("pedagogy", "Supervision")
    Supervision.objects.filter(tandem__isnull=True).update(is_tandem_prophylactic=None)


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0009_remove_supervision_school_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervision',
            name='is_tandem_prophylactic',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Tandem prophylaktisch'),
        ),
        migrations.RunPython(
            fix_existing_tandem_prophylactic,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
