# Generated by Django 5.2.12 on 2026-04-03 08:18

from django.db import migrations, models
from django.db.models import F


def fix_tandem_prophylactic(apps, schema_editor):
    Supervision = apps.get_model("pedagogy", "Supervision")
    Supervision.objects.filter(is_tandem_prophylactic__isnull=True).update(
        is_tandem_prophylactic=F("is_prophylactic")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0010_alter_supervision_is_tandem_prophylactic"),
    ]

    operations = [
        migrations.RunPython(
            fix_tandem_prophylactic,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="supervision",
            name="is_tandem_prophylactic",
            field=models.BooleanField(
                default=False, verbose_name="Tandem prophylaktisch"
            ),
        ),
    ]
