# Generated by Django 5.2.12 on 2026-04-04 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0011_alter_supervision_is_tandem_prophylactic"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervision",
            name="months_override",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Manuelle Überschreibung der berechneten Monate.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Monate (überschrieben)",
            ),
        ),
    ]
