# Generated by Django 5.2.12 on 2026-04-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0014_supervision_monthly_installment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervision',
            name='months_override',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='school_days_override',
        ),
    ]
