# Generated by Django 5.2.12 on 2026-04-09 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0015_remove_supervision_months_override_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchulAuswertung",
            fields=[],
            options={
                "verbose_name": "Schulauswertung",
                "verbose_name_plural": "Schulauswertungen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pedagogy.supervision",),
        ),
    ]
