# Generated by Django 5.2.12 on 2026-04-10 08:40 (hand-edited to split data migration)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0016_schulauswertung"),
    ]

    operations = [
        # Create TandemPairing – tandem/is_tandem_prophylactic still exist here
        # so the data migration (0018) can read them.
        migrations.CreateModel(
            name="TandemPairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tandembetreuung",
                "verbose_name_plural": "Tandembetreuungen",
            },
        ),
        migrations.AddField(
            model_name="tandempairing",
            name="supervision_a",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tandem_as_a",
                to="pedagogy.supervision",
                verbose_name="Betreuung A",
            ),
        ),
        migrations.AddField(
            model_name="tandempairing",
            name="supervision_b",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tandem_as_b",
                to="pedagogy.supervision",
                verbose_name="Betreuung B",
            ),
        ),
        # Rename proxy: SchulAuswertung → SchoolReport
        migrations.DeleteModel(
            name="SchulAuswertung",
        ),
        migrations.CreateModel(
            name="SchoolReport",
            fields=[],
            options={
                "verbose_name": "Schulauswertung",
                "verbose_name_plural": "Schulauswertungen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pedagogy.supervision",),
        ),
        # tandem + is_tandem_prophylactic are removed in 0019,
        # AFTER the data migration (0018) has run.
    ]
