# Generated by Django 5.2.12 on 2026-04-10 10:48

from django.db import migrations, models


def migrate_in_coordination_to_in_review(apps, schema_editor):
    Request = apps.get_model("pedagogy", "Request")
    Request.objects.filter(state="in_coordination").update(state="in_review")


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0019_remove_tandem_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="approval_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("phone", "Telefonisch"),
                    ("email", "Per Mail"),
                    ("notice", "Per Bescheid"),
                ],
                max_length=20,
                verbose_name="Art der Genehmigung",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="decision_date",
            field=models.DateField(
                blank=True,
                help_text="Datum der Genehmigung oder Ablehnung.",
                null=True,
                verbose_name="Entscheidungsdatum",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("in_review", "In Prüfung"),
                    ("rejected", "Abgelehnt"),
                    ("approved", "Genehmigt"),
                ],
                default="draft",
                max_length=50,
                verbose_name="Zustand",
            ),
        ),
        migrations.RunPython(
            migrate_in_coordination_to_in_review,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
