# Generated by Django 5.2.12 on 2026-04-14 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0020_request_approval_type_request_decision_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewRequest",
            fields=[],
            options={
                "verbose_name": "Neuantrag",
                "verbose_name_plural": "Neuanträge",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pedagogy.supervision",),
        ),
    ]
