# Generated by Django 5.2.12 on 2026-04-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0021_newrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandempairing',
            name='supervision_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tandem_as_a', to='pedagogy.supervision', verbose_name='Betreuung A'),
        ),
        migrations.AlterField(
            model_name='tandempairing',
            name='supervision_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tandem_as_b', to='pedagogy.supervision', verbose_name='Betreuung B'),
        ),
    ]
