# Generated by Django 5.2.12 on 2026-04-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0022_alter_tandempairing_supervision_a_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefonnummer"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-Mail"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Notizen"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="pedagogy.school",
                        verbose_name="Schule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ansprechperson",
                "verbose_name_plural": "Ansprechpersonen",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
