# Generated by Django 5.2.12 on 2026-04-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0024_school_city_school_district_school_house_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="guardian_first_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Erziehungsberechtigte:r – Vorname",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_last_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Erziehungsberechtigte:r – Nachname",
            ),
        ),
    ]
