# Generated by Django 5.2.12 on 2026-03-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-primary', 'street'], 'verbose_name': 'Adresse', 'verbose_name_plural': 'Adressen'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['holder'], 'verbose_name': 'Bankverbindung', 'verbose_name_plural': 'Bankverbindungen'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-primary'], 'verbose_name': 'E-Mail-Adresse', 'verbose_name_plural': 'E-Mail-Adressen'},
        ),
        migrations.AlterModelOptions(
            name='externalidentifier',
            options={'ordering': ['label'], 'verbose_name': 'Identifikator', 'verbose_name_plural': 'Identifikatoren'},
        ),
        migrations.AlterModelOptions(
            name='masterdata',
            options={'ordering': ['name'], 'verbose_name': 'Stammdaten', 'verbose_name_plural': 'Stammdaten'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-primary'], 'verbose_name': 'Telefonnummer', 'verbose_name_plural': 'Telefonnummern'},
        ),
        migrations.AlterField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='email',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='externalidentifier',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
