# Generated by Django 5.2.12 on 2026-03-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_address_options_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalidentifier',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='MasterData',
        ),
        migrations.DeleteModel(
            name='ExternalIdentifier',
        ),
    ]
