# Generated by Django 4.2.28 on 2026-03-16 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Country",
        ),
    ]
