# Generated by Django 4.2.28 on 2026-03-16 16:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_delete_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="telephone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="DE", verbose_name="Telefonnummer"
            ),
        ),
    ]
