# Generated by Django 5.2.12 on 2026-03-31 09:41

import base.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_member_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", base.fields.MonthField(unique=True, verbose_name="Monat")),
                ("school_days", models.PositiveIntegerField(verbose_name="Schultage")),
                (
                    "public_holidays",
                    models.PositiveIntegerField(verbose_name="Feiertage"),
                ),
                (
                    "vacation_days",
                    models.PositiveIntegerField(verbose_name="Urlaubstage"),
                ),
            ],
            options={
                "verbose_name": "Schultage",
                "verbose_name_plural": "Schultage",
                "ordering": ["-month"],
            },
        ),
    ]
