# Generated by Django 5.2.12 on 2026-04-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_schooldays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Telefonnummer'),
        ),
    ]
