# Generated by Django 5.2.12 on 2026-04-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_phone_number_to_charfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Vorname"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Nachname"
            ),
        ),
    ]
