# Generated by Django 5.2.12 on 2026-03-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_address_options_alter_bankaccount_options_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Mitglied', 'verbose_name_plural': 'Mitglieder'},
        ),
        migrations.AlterField(
            model_name='member',
            name='authorization_id',
            field=models.CharField(help_text='Referenznummer des SEPA-Lastschriftmandats', max_length=100, verbose_name='Mandatsreferenz-Nr.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, help_text='Monatlicher Mitgliedsbeitrag in Euro', max_digits=10, verbose_name='Beitragshöhe'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('leaving_date__isnull', True), ('leaving_date__gte', models.F('entrance_date')), _connector='OR'), name='member_leaving_date_after_entrance_date'),
        ),
    ]
