# Generated by Django 5.2.12 on 2026-03-24 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('pedagogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='supervision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogy.supervision', verbose_name='Betreuung'),
        ),
        migrations.AddField(
            model_name='poolagreement',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.costpayer', verbose_name='Kostenträger'),
        ),
    ]
