# Generated by Django 5.2.12 on 2026-03-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolagreement',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_agreements', to='finance.costpayer', verbose_name='Kostenträger'),
        ),
    ]
