# Generated by Django 5.2.11 on 2026-03-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeagreement",
            name="responsible_payer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.costpayer",
                verbose_name="Zuständiger Kostenzahler",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CostPayerLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.costpayer",
                        verbose_name="Kostenzahler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kostenzahler-Verknüpfung",
                "verbose_name_plural": "Kostenzahler-Verknüpfungen",
            },
        ),
    ]
