# Generated by Django 5.2.12 on 2026-03-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_add_costpayercontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costpayercontact",
            name="notes",
            field=models.CharField(blank=True, max_length=100, verbose_name="Notizen"),
        ),
    ]
