# Generated by Django 5.2.11 on 2026-03-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_feeagreement_responsible_payer_costpayerlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeagreement",
            name="additional_payers",
            field=models.ManyToManyField(
                blank=True,
                related_name="additional_fee_agreements",
                to="finance.costpayer",
                verbose_name="Weitere Kostenzahler",
            ),
        ),
        migrations.AlterField(
            model_name="feeagreement",
            name="responsible_payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_fee_agreements",
                to="finance.costpayer",
                verbose_name="Zuständiger Kostenzahler",
            ),
        ),
        migrations.DeleteModel(
            name="CostPayerLink",
        ),
    ]
