# Generated by Django 5.2.12 on 2026-03-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_poolagreement_payer'),
        ('pedagogy', '0002_poolschoolagreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costpayer',
            options={'ordering': ['identifier'], 'verbose_name': 'Kostenträger', 'verbose_name_plural': 'Kostenträger'},
        ),
        migrations.AlterModelOptions(
            name='feeagreement',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Entgeltvereinbarung', 'verbose_name_plural': 'Entgeltvereinbarungen'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Zahlung', 'verbose_name_plural': 'Zahlungen'},
        ),
        migrations.AlterModelOptions(
            name='poolagreement',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Poolvereinbarung', 'verbose_name_plural': 'Poolvereinbarungen'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.costpayer', verbose_name='Kostenträger'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='supervision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pedagogy.supervision', verbose_name='Betreuung'),
        ),
        migrations.AddConstraint(
            model_name='feeagreement',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='feeagreement_valid_to_after_valid_from'),
        ),
        migrations.AddConstraint(
            model_name='poolagreement',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='poolagreement_valid_to_after_valid_from'),
        ),
    ]
