# Generated by Django 5.2.12 on 2026-03-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_alter_costpayercontact_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(db_index=True, verbose_name="Zahlungsdatum"),
        ),
        migrations.AlterField(
            model_name="salaryagreement",
            name="valid_from",
            field=models.DateField(db_index=True, verbose_name="Gültig von"),
        ),
    ]
