# Generated by Django 5.2.12 on 2026-03-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_installment_poolagreement_flat_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeagreement',
            name='label',
        ),
    ]
