# Generated by Django 5.2.12 on 2026-03-30 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_payment_note_not_null"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="salaryagreement",
            table=None,
        ),
    ]
