# Generated by Django 5.2.12 on 2026-03-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_replace_max_supervisions"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="booking_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Buchungsnummer"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Zahlungsdatum"),
        ),
    ]
