# Generated by Django 5.2.12 on 2026-03-31 09:30

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_rename_billing_period_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeagreement',
            name='price_honorary_standard',
        ),
        migrations.RemoveField(
            model_name='feeagreement',
            name='price_honorary_tandem',
        ),
        migrations.AddField(
            model_name='salaryagreement',
            name='salary_honorary_standard',
            field=base.fields.EuroDecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Schulbegleitung (Ehrenamt)'),
        ),
        migrations.AddField(
            model_name='salaryagreement',
            name='salary_honorary_tandem',
            field=base.fields.EuroDecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tandem (Ehrenamt)'),
        ),
    ]
