# Generated by Django 5.2.12 on 2026-04-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0017_alter_monthlycontractcost_gross_personnel_costs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costpayercontact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Telefonnummer"
            ),
        ),
    ]
