# Generated by Django 5.2.12 on 2026-03-24 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Beginn')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Ende')),
                ('reason', models.CharField(choices=[('illness', 'Krankheit'), ('child_sick', 'Kind Krank'), ('appointment', 'Termin'), ('other', 'Sonstiges')], max_length=50, verbose_name='Grund')),
                ('certificate', models.BooleanField(default=False, verbose_name='Mit AU')),
            ],
            options={
                'verbose_name': 'Abwesenheit',
                'verbose_name_plural': 'Abwesenheiten',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.person')),
                ('application_date', models.DateField(verbose_name='Datum der Bewerbung')),
                ('desired_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Stundenwunsch')),
                ('notice_period', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kündigungsfristen')),
                ('suitability_rating', models.CharField(blank=True, max_length=255, null=True, verbose_name='Einstufung nach Eignung')),
            ],
            options={
                'verbose_name': 'Bewerber:in',
                'verbose_name_plural': 'Bewerber:innen',
            },
            bases=('base.person',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.person')),
                ('maiden_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geburtsname')),
                ('birthday', models.DateField(verbose_name='Geburtstag')),
                ('birthplace', models.CharField(max_length=255, verbose_name='Geburtsort')),
                ('country_of_birth', models.CharField(choices=[('DE', 'Deutschland'), ('YU', 'Jugoslawien'), ('AL', 'Albanien'), ('BA', 'Bosnien und Herzegowina'), ('AD', 'Andorra'), ('BE', 'Belgien'), ('BG', 'Bulgarien'), ('DK', 'Dänemark'), ('EE', 'Estland'), ('FI', 'Finnland'), ('FR', 'Frankreich'), ('HR', 'Kroatien'), ('SI', 'Slowenien'), ('CS', 'Serbien und Montenegro'), ('RS', 'Serbien'), ('GR', 'Griechenland'), ('IE', 'Irland'), ('IS', 'Island'), ('IT', 'Italien'), ('YU', 'Bundesrepublik Jugoslawien'), ('LV', 'Lettland'), ('ME', 'Montenegro'), ('LI', 'Liechtenstein'), ('LT', 'Litauen'), ('LU', 'Luxemburg'), ('MK', 'Nordmazedonien'), ('MT', 'Malta'), ('MD', 'Republik Moldau'), ('MC', 'Monaco'), ('NL', 'Königreich der Niederlande'), ('NO', 'Norwegen'), ('XK', 'Kosovo'), ('AT', 'Österreich'), ('PL', 'Polen'), ('PT', 'Portugal'), ('RO', 'Rumänien'), ('SK', 'Slowakei'), ('SM', 'San Marino'), ('SE', 'Schweden'), ('CH', 'Schweiz'), ('SU', 'Sowjetunion'), ('RU', 'Russische Föderation'), ('ES', 'Spanien'), ('CS', 'Tschechoslowakei'), ('TR', 'Türkei'), ('CZ', 'Tschechien'), ('HU', 'Ungarn'), ('UA', 'Ukraine'), ('VA', 'Vatikanstadt'), ('GB', 'Vereinigtes Königreich'), ('BY', 'Belarus'), ('RS', 'Serbien'), ('CY', 'Zypern'), ('DZ', 'Algerien'), ('AO', 'Angola'), ('ER', 'Eritrea'), ('ET', 'Äthiopien'), ('LS', 'Lesotho'), ('BW', 'Botsuana'), ('BJ', 'Benin'), ('DJ', 'Dschibuti'), ('CI', 'Côte d’Ivoire'), ('NG', 'Nigeria'), ('ZW', 'Simbabwe'), ('GA', 'Gabun'), ('GM', 'Gambia'), ('GH', 'Ghana'), ('MR', 'Mauretanien'), ('CV', 'Cabo Verde'), ('KE', 'Kenia'), ('KM', 'Komoren'), ('CG', 'Kongo'), ('CD', 'Demokratische Republik Kongo'), ('LR', 'Liberia'), ('LY', 'Libyen'), ('MG', 'Madagaskar'), ('ML', 'Mali'), ('MA', 'Marokko'), ('MU', 'Mauritius'), ('MZ', 'Mosambik'), ('NE', 'Niger'), ('MW', 'Malawi'), ('ZM', 'Sambia'), ('BF', 'Burkina Faso'), ('GW', 'Guinea-Bissau'), ('GN', 'Guinea'), ('CM', 'Kamerun'), ('ZA', 'Südafrika'), ('RW', 'Ruanda'), ('NA', 'Namibia'), ('ST', 'São Tomé und Príncipe'), ('SN', 'Senegal'), ('SC', 'Seychellen'), ('SL', 'Sierra Leone'), ('SO', 'Somalia'), ('GQ', 'Äquatorialguinea'), ('SD', 'Sudan'), ('SD', 'Sudan'), ('SS', 'Südsudan'), ('SZ', 'Eswatini'), ('TZ', 'Vereinigte Republik Tansania'), ('TG', 'Togo'), ('TD', 'Tschad'), ('TN', 'Tunesien'), ('UG', 'Uganda'), ('EG', 'Ägypten'), ('CF', 'Zentralafrikanische Republik'), ('BI', 'Burundi'), ('AG', 'Antigua und Barbuda'), ('BB', 'Barbados'), ('AR', 'Argentinien'), ('BS', 'Bahamas'), ('BO', 'Plurinationaler Staat Bolivien'), ('BR', 'Brasilien'), ('GY', 'Guyana'), ('BZ', 'Belize'), ('CL', 'Chile'), ('DM', 'Dominica'), ('CR', 'Costa Rica'), ('DO', 'Dominikanische Republik'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GD', 'Grenada'), ('GT', 'Guatemala'), ('HT', 'Haiti'), ('HN', 'Honduras'), ('CA', 'Kanada'), ('CO', 'Kolumbien'), ('CU', 'Kuba'), ('MX', 'Mexiko'), ('NI', 'Nicaragua'), ('JM', 'Jamaika'), ('PA', 'Panama'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('SR', 'Suriname'), ('UY', 'Uruguay'), ('LC', 'St. Lucia'), ('VE', 'Bolivarische Republik Venezuela'), ('US', 'Vereinigte Staaten'), ('VC', 'St. Vincent und die Grenadinen'), ('KN', 'St. Kitts und Nevis'), ('TT', 'Trinidad und Tobago'), ('HK', 'Hongkong'), ('MO', 'Macau'), ('YE', 'Jemen'), ('AM', 'Armenien'), ('AF', 'Afghanistan'), ('BH', 'Bahrain'), ('AZ', 'Aserbaidschan'), ('BT', 'Bhutan'), ('MM', 'Myanmar'), ('BN', 'Brunei Darussalam'), ('GE', 'Georgien'), ('LK', 'Sri Lanka'), ('VN', 'Vietnam'), ('KP', 'Demokratische Volksrepublik Korea'), ('IN', 'Indien'), ('ID', 'Indonesien'), ('IQ', 'Irak'), ('IR', 'Islamische Republik Iran'), ('IL', 'Israel'), ('JP', 'Japan'), ('KZ', 'Kasachstan'), ('JO', 'Jordanien'), ('KH', 'Kambodscha'), ('QA', 'Katar'), ('KW', 'Kuwait'), ('LA', 'Demokratische Volksrepublik Laos'), ('KG', 'Kirgisistan'), ('LB', 'Libanon'), ('MV', 'Malediven'), ('OM', 'Oman'), ('MN', 'Mongolei'), ('NP', 'Nepal'), ('BD', 'Bangladesch'), ('PK', 'Pakistan'), ('PH', 'Philippinen'), ('TW', 'Taiwan'), ('KR', 'Republik Korea'), ('AE', 'Vereinigte Arabische Emirate'), ('TJ', 'Tadschikistan'), ('TM', 'Turkmenistan'), ('SA', 'Saudi-Arabien'), ('SG', 'Singapur'), ('SY', 'Arabische Republik Syrien'), ('TH', 'Thailand'), ('UZ', 'Usbekistan'), ('CN', 'China'), ('MY', 'Malaysia'), ('TL', 'Timor-Leste'), ('AU', 'Australien'), ('SB', 'Salomonen'), ('FJ', 'Fidschi'), ('KI', 'Kiribati'), ('NR', 'Nauru'), ('VU', 'Vanuatu'), ('NZ', 'Neuseeland'), ('PW', 'Palau'), ('PG', 'Papua-Neuguinea'), ('TV', 'Tuvalu'), ('TO', 'Tonga'), ('WS', 'Samoa'), ('MH', 'Marshallinseln'), ('FM', 'Föderierte Staaten von Mikronesien')], default='DE', max_length=2, verbose_name='Geburtsland')),
                ('citizenship', models.CharField(choices=[('000', 'deutsch'), ('120', 'jugoslawisch'), ('121', 'albanisch'), ('122', 'bosnisch-herzegowinisch'), ('123', 'andorranisch'), ('124', 'belgisch'), ('125', 'bulgarisch'), ('126', 'dänisch'), ('127', 'estnisch'), ('128', 'finnisch'), ('129', 'französisch'), ('130', 'kroatisch'), ('131', 'slowenisch'), ('132', 'von Serbien und Montenegro'), ('133', 'serbisch'), ('134', 'griechisch'), ('135', 'irisch'), ('136', 'isländisch'), ('137', 'italienisch'), ('138', 'jugoslawisch'), ('139', 'lettisch'), ('140', 'montenegrinisch'), ('141', 'liechtensteinisch'), ('142', 'litauisch'), ('143', 'luxemburgisch'), ('144', 'mazedonisch/Bürger der Republik Nordmazedonien'), ('145', 'maltesisch'), ('146', 'moldauisch'), ('147', 'monegassisch'), ('148', 'niederländisch'), ('149', 'norwegisch'), ('150', 'kosovarisch'), ('151', 'österreichisch'), ('152', 'polnisch'), ('153', 'portugiesisch'), ('154', 'rumänisch'), ('155', 'slowakisch'), ('156', 'san-marinesisch'), ('157', 'schwedisch'), ('158', 'schweizerisch'), ('159', 'sowjetisch'), ('160', 'russisch'), ('161', 'spanisch'), ('162', 'tschechoslowakisch'), ('163', 'türkisch'), ('164', 'tschechisch'), ('165', 'ungarisch'), ('166', 'ukrainisch'), ('167', 'vatikanisch'), ('168', 'britisch'), ('169', 'belarussisch'), ('170', 'serbisch'), ('181', 'zyprisch'), ('221', 'algerisch'), ('223', 'angolanisch'), ('224', 'eritreisch'), ('225', 'äthiopisch'), ('226', 'lesothisch'), ('227', 'botsuanisch'), ('229', 'beninisch'), ('230', 'dschibutisch'), ('231', 'ivorisch'), ('232', 'nigerianisch'), ('233', 'simbabwisch'), ('236', 'gabunisch'), ('237', 'gambisch'), ('238', 'ghanaisch'), ('239', 'mauretanisch'), ('242', 'cabo-verdisch'), ('243', 'kenianisch'), ('244', 'komorisch'), ('245', 'kongolesisch'), ('246', 'der Demokratischen Republik Kongo'), ('247', 'liberianisch'), ('248', 'libysch'), ('249', 'madagassisch'), ('251', 'malisch'), ('252', 'marokkanisch'), ('253', 'mauritisch'), ('254', 'mosambikanisch'), ('255', 'nigrisch'), ('256', 'malawisch'), ('257', 'sambisch'), ('258', 'burkinisch'), ('259', 'guinea-bissauisch'), ('261', 'guineisch'), ('262', 'kamerunisch'), ('263', 'südafrikanisch'), ('265', 'ruandisch'), ('267', 'namibisch'), ('268', 'são-toméisch'), ('269', 'senegalesisch'), ('271', 'seychellisch'), ('272', 'sierra-leonisch'), ('273', 'somalisch'), ('274', 'äquatorialguineisch'), ('276', 'sudanesisch'), ('277', 'sudanesisch'), ('278', 'südsudanesisch'), ('281', 'eswatinisch'), ('282', 'tansanisch'), ('283', 'togoisch'), ('284', 'tschadisch'), ('285', 'tunesisch'), ('286', 'ugandisch'), ('287', 'ägyptisch'), ('289', 'zentralafrikanisch'), ('291', 'burundisch'), ('320', 'antiguanisch'), ('322', 'barbadisch'), ('323', 'argentinisch'), ('324', 'bahamaisch'), ('326', 'bolivianisch'), ('327', 'brasilianisch'), ('328', 'guyanisch'), ('330', 'belizisch'), ('332', 'chilenisch'), ('333', 'dominicanisch'), ('334', 'costa-ricanisch'), ('335', 'dominikanisch'), ('336', 'ecuadorianisch'), ('337', 'salvadorianisch'), ('340', 'grenadisch'), ('345', 'guatemaltekisch'), ('346', 'haitianisch'), ('347', 'honduranisch'), ('348', 'kanadisch'), ('349', 'kolumbianisch'), ('351', 'kubanisch'), ('353', 'mexikanisch'), ('354', 'nicaraguanisch'), ('355', 'jamaikanisch'), ('357', 'panamaisch'), ('359', 'paraguayisch'), ('361', 'peruanisch'), ('364', 'surinamisch'), ('365', 'uruguayisch'), ('366', 'lucianisch'), ('367', 'venezolanisch'), ('368', 'amerikanisch'), ('369', 'vincentisch'), ('370', 'von St. Kitts und Nevis'), ('371', 'von Trinidad und Tobago'), ('411', 'chinesisch (Hongkong)'), ('412', 'chinesisch (Macau)'), ('421', 'jemenitisch'), ('422', 'armenisch'), ('423', 'afghanisch'), ('424', 'bahrainisch'), ('425', 'aserbaidschanisch'), ('426', 'bhutanisch'), ('427', 'myanmarisch'), ('429', 'bruneiisch'), ('430', 'georgisch'), ('431', 'sri-lankisch'), ('432', 'vietnamesisch'), ('434', 'der Demokratischen Volksrepublik Korea'), ('436', 'indisch'), ('437', 'indonesisch'), ('438', 'irakisch'), ('439', 'iranisch'), ('441', 'israelisch'), ('442', 'japanisch'), ('444', 'kasachisch'), ('445', 'jordanisch'), ('446', 'kambodschanisch'), ('447', 'katarisch'), ('448', 'kuwaitisch'), ('449', 'laotisch'), ('450', 'kirgisisch'), ('451', 'libanesisch'), ('454', 'maledivisch'), ('456', 'omanisch'), ('457', 'mongolisch'), ('458', 'nepalesisch'), ('460', 'bangladeschisch'), ('461', 'pakistanisch'), ('462', 'philippinisch'), ('465', 'taiwanisch'), ('467', 'der Republik Korea'), ('469', 'der Vereinigten Arabischen Emirate'), ('470', 'tadschikisch'), ('471', 'turkmenisch'), ('472', 'saudi-arabisch'), ('474', 'singapurisch'), ('475', 'syrisch'), ('476', 'thailändisch'), ('477', 'usbekisch'), ('479', 'chinesisch'), ('482', 'malaysisch'), ('483', 'von Timor-Leste'), ('523', 'australisch'), ('524', 'salomonisch'), ('526', 'fidschianisch'), ('530', 'kiribatisch'), ('531', 'nauruisch'), ('532', 'vanuatuisch'), ('536', 'neuseeländisch'), ('537', 'palauisch'), ('538', 'papua-neuguineisch'), ('540', 'tuvaluisch'), ('541', 'tongaisch'), ('543', 'samoanisch'), ('544', 'marshallisch'), ('545', 'mikronesisch')], default='000', max_length=3, verbose_name='Staatsangehörigkeit')),
                ('personnel_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal-Nr. Lohnprogramm')),
                ('marital_status', models.CharField(choices=[('single', 'ledig'), ('married', 'verheiratet'), ('divorced', 'geschieden'), ('widowed', 'verwitwet'), ('other', 'sonstiges')], max_length=50, verbose_name='Familienstand')),
                ('number_of_children', models.PositiveIntegerField(default=0, verbose_name='Kinderzahl')),
                ('social_security_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sozialversicherungs-Nr.')),
                ('tax_id', models.CharField(max_length=50, verbose_name='Steuer-ID')),
                ('tax_class', models.CharField(blank=True, choices=[('1', 'Klasse 1'), ('2', 'Klasse 2'), ('3', 'Klasse 3'), ('4', 'Klasse 4'), ('5', 'Klasse 5'), ('6', 'Klasse 6')], max_length=10, null=True, verbose_name='Steuerklasse')),
                ('health_insurance', models.CharField(max_length=255, verbose_name='Krankenkasse')),
                ('severe_disability_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='GdB (Prozentsatz)')),
                ('measles_protection', models.BooleanField(default=False, verbose_name='Nachweis Masernschutz')),
                ('criminal_record_certificate', models.DateField(verbose_name='Erweitertes Führungszeugnis (Datum)')),
                ('risk_assessment', models.TextField(blank=True, null=True, verbose_name='Erläut. Gefährdungsbeurteilung')),
                ('lh_start', models.DateField(blank=True, null=True, verbose_name='Beschäftigt bei LH seit')),
            ],
            options={
                'verbose_name': 'Angestellte:r',
                'verbose_name_plural': 'Angestellte',
            },
            bases=('base.person',),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Beginn Arbeitsverhältnis')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ende Arbeitsverhältnis')),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Stundenumfang')),
            ],
            options={
                'verbose_name': 'Arbeitsverhältnis',
                'verbose_name_plural': 'Arbeitsverhältnisse',
            },
        ),
        migrations.CreateModel(
            name='OtherEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arbeitgeber (Sonstige)')),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Stundenumfang')),
            ],
            options={
                'verbose_name': 'Weiteres Arbeitsverhältnis',
                'verbose_name_plural': 'Weitere Arbeitsverhältnisse',
            },
        ),
        migrations.CreateModel(
            name='SalaryAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_standard', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Schulbegleitung (allgemein)')),
                ('salary_tandem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tandem')),
                ('salary_coordination', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Koordination')),
                ('salary_management', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Geschäftsführung')),
                ('valid_from', models.DateField(verbose_name='Gültig von')),
                ('valid_to', models.DateField(verbose_name='Gültig bis')),
            ],
            options={
                'verbose_name': 'Gehaltsvereinbarung',
                'verbose_name_plural': 'Gehaltsvereinbarungen',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Gültig von')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
            ],
            options={
                'verbose_name': 'Fortbildungsnachweis',
                'verbose_name_plural': 'Fortbildungsnachweise',
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Fortbildungstyp',
                'verbose_name_plural': 'Fortbildungstypen',
            },
        ),
        migrations.CreateModel(
            name='VocationalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('qualified', models.BooleanField(default=False, verbose_name='Qualifiziert')),
            ],
            options={
                'verbose_name': 'Berufsbildung',
                'verbose_name_plural': 'Berufsbildungen',
            },
        ),
    ]
