# Generated by Django 5.2.12 on 2026-03-24 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        ('pedagogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='desired_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedagogy.school', verbose_name='Schulwunsch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='church_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.denomination', verbose_name='Kirchenmitgliedschaft'),
        ),
        migrations.AddField(
            model_name='absence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee', verbose_name='Mitarbeiter:in'),
        ),
        migrations.AddField(
            model_name='employment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='hr.employee', verbose_name='Mitarbeiter:in'),
        ),
        migrations.AddField(
            model_name='otheremployment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_employments', to='hr.employee', verbose_name='Mitarbeiter:in'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee', verbose_name='Personalfall'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.trainingtype', verbose_name='Fortbildungstyp'),
        ),
        migrations.AddField(
            model_name='employee',
            name='vocational_trainings',
            field=models.ManyToManyField(blank=True, to='hr.vocationaltraining', verbose_name='Berufsbildungen'),
        ),
    ]
