# Generated by Django 5.2.12 on 2026-03-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_address_options_alter_bankaccount_options_and_more'),
        ('hr', '0002_initial'),
        ('pedagogy', '0002_poolschoolagreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['-start'], 'verbose_name': 'Abwesenheit', 'verbose_name_plural': 'Abwesenheiten'},
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-application_date'], 'verbose_name': 'Bewerber:in', 'verbose_name_plural': 'Bewerber:innen'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Angestellte:r', 'verbose_name_plural': 'Angestellte'},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'ordering': ['-start_date'], 'verbose_name': 'Arbeitsverhältnis', 'verbose_name_plural': 'Arbeitsverhältnisse'},
        ),
        migrations.AlterModelOptions(
            name='otheremployment',
            options={'ordering': ['employee__last_name', 'employee__first_name', 'employer'], 'verbose_name': 'Weiteres Arbeitsverhältnis', 'verbose_name_plural': 'Weitere Arbeitsverhältnisse'},
        ),
        migrations.AlterModelOptions(
            name='salaryagreement',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Gehaltsvereinbarung', 'verbose_name_plural': 'Gehaltsvereinbarungen'},
        ),
        migrations.AlterModelOptions(
            name='trainingrecord',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Fortbildungsnachweis', 'verbose_name_plural': 'Fortbildungsnachweise'},
        ),
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'ordering': ['name'], 'verbose_name': 'Fortbildungstyp', 'verbose_name_plural': 'Fortbildungstypen'},
        ),
        migrations.AlterModelOptions(
            name='vocationaltraining',
            options={'ordering': ['name'], 'verbose_name': 'Berufsbildung', 'verbose_name_plural': 'Berufsbildungen'},
        ),
        migrations.AlterField(
            model_name='absence',
            name='certificate',
            field=models.BooleanField(default=False, help_text='Liegt eine ärztliche Arbeitsunfähigkeitsbescheinigung vor?', verbose_name='Mit AU'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='hr.employee', verbose_name='Mitarbeiter:in'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='desired_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='pedagogy.school', verbose_name='Schulwunsch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='church_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='base.denomination', verbose_name='Kirchenmitgliedschaft'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='criminal_record_certificate',
            field=models.DateField(help_text='Ausstellungsdatum des erweiterten Führungszeugnisses (§ 30a BZRG)', verbose_name='Erweitertes Führungszeugnis (Datum)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lh_start',
            field=models.DateField(blank=True, help_text='Erstmaliger Beschäftigungsbeginn bei der Lebenshilfe', null=True, verbose_name='Beschäftigt bei LH seit'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personnel_number',
            field=models.CharField(blank=True, help_text='Personalnummer im Lohnprogramm (optional)', max_length=50, null=True, verbose_name='Personal-Nr. Lohnprogramm'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='severe_disability_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Anerkannter GdB in Prozent. Leer lassen, wenn keine Schwerbehinderung vorliegt.', null=True, verbose_name='GdB (Prozentsatz)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(blank=True, help_text='12-stellige Sozialversicherungsnummer', max_length=50, null=True, verbose_name='Sozialversicherungs-Nr.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_id',
            field=models.CharField(help_text='11-stellige Steueridentifikationsnummer', max_length=50, verbose_name='Steuer-ID'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, help_text='Wöchentlicher Stundenumfang laut Arbeitsvertrag', max_digits=5, verbose_name='Stundenumfang'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='hr.employee', verbose_name='Personalfall'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='hr.trainingtype', verbose_name='Fortbildungstyp'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Leer lassen, wenn die Fortbildung dauerhaft gültig ist', null=True, verbose_name='Gültig bis'),
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.CheckConstraint(condition=models.Q(('start__isnull', True), ('end__isnull', True), ('end__gte', models.F('start')), _connector='OR'), name='absence_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='employment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='employment_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='salaryagreement',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='salaryagreement_valid_to_after_valid_from'),
        ),
        migrations.AddConstraint(
            model_name='trainingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='trainingrecord_valid_to_after_valid_from'),
        ),
    ]
