# Generated by Django 4.2.28 on 2026-03-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="citizenship",
            field=models.CharField(
                choices=[], max_length=3, verbose_name="Staatsangehörigkeit"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="country_of_birth",
            field=models.CharField(
                choices=[], max_length=2, verbose_name="Geburtsland"
            ),
        ),
    ]
