# Generated by Django 5.2.12 on 2026-03-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_absence_options_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.CharField(choices=[('illness', 'Krankheit'), ('child_sick', 'Kind krank'), ('appointment', 'Termin'), ('other', 'Sonstiges')], max_length=50, verbose_name='Grund'),
        ),
    ]
