# Generated by Django 5.2.12 on 2026-03-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_employee_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='denomination',
            table=None,
        ),
    ]
