# Generated by Django 5.2.12 on 2026-03-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_alter_denomination_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='desired_hours',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='suitability_rating',
        ),
        migrations.AddField(
            model_name='applicant',
            name='desired_hours_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Stundenwunsch (bis)'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='desired_hours_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Stundenwunsch (von)'),
        ),
    ]
