# Generated by Django 5.2.12 on 2026-04-04 20:43

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_employment_weekly_hours_and_work_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='weekly_hours',
            field=base.fields.HourMinuteDurationField(help_text='Wöchentlicher Stundenumfang laut Arbeitsvertrag', verbose_name='Wochenstunden'),
        ),
    ]
