# Generated by Django 5.2.12 on 2026-04-05 17:03

import base.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0021_alter_employment_weekly_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="employment",
            name="calculation_cache",
            field=models.JSONField(
                blank=True, editable=False, null=True, verbose_name="Berechnungs-Cache"
            ),
        ),
        migrations.AddField(
            model_name="employment",
            name="gross_salary_contract",
            field=base.fields.EuroDecimalField(
                blank=True,
                decimal_places=2,
                help_text="Gespeichertes Ergebnis der Gehaltsberechnung (rechnerisch oder überschrieben)",
                max_digits=10,
                null=True,
                verbose_name="Brutto laut Vertrag",
            ),
        ),
        migrations.AddField(
            model_name="employment",
            name="overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Überschreibt berechnete Felder: {work_days, months, gross_salary}",
                verbose_name="Überschreibungen",
            ),
        ),
        migrations.AddField(
            model_name="employment",
            name="version",
            field=models.CharField(
                choices=[("2026", "2026")],
                default="2026",
                max_length=10,
                verbose_name="Berechnungsversion",
            ),
        ),
    ]
