# Generated by Django 5.2.12 on 2026-04-07 16:14

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_alter_employment_weekly_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='gross_salary_override',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='month_override',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='work_days_override',
        ),
        migrations.AddField(
            model_name='employment',
            name='gross_salary',
            field=base.fields.EuroDecimalField(blank=True, decimal_places=2, help_text='Monatliches Bruttogehalt laut Arbeitsvertrag', max_digits=10, null=True, verbose_name='Brutto laut Vertrag'),
        ),
    ]
