# Generated by Django 5.2.12 on 2026-04-05 17:03

from django.db import migrations


def migrate_overrides(apps, schema_editor):
    """
    Migrate three individual override fields into the consolidated overrides JSONField.
    The gross_salary_contract is NOT populated here because it requires the full
    strategy logic including DB lookups. Use the management command
    'populate_gross_salary_contract' after this migration runs.
    """
    Employment = apps.get_model("hr", "Employment")
    for emp in Employment.objects.all():
        overrides = {}
        if emp.work_days_override is not None:
            overrides["work_days"] = emp.work_days_override
        if emp.month_override is not None:
            overrides["months"] = str(emp.month_override)
        if emp.gross_salary_override is not None:
            overrides["gross_salary"] = str(emp.gross_salary_override)
        if overrides:
            emp.overrides = overrides
            emp.save(update_fields=["overrides"])


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0022_employment_strategy_fields"),
    ]

    operations = [
        migrations.RunPython(migrate_overrides, migrations.RunPython.noop),
    ]
