# Generated by Django 5.2.12 on 2026-04-05 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0023_migrate_overrides_to_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employment",
            name="gross_salary_override",
        ),
        migrations.RemoveField(
            model_name="employment",
            name="month_override",
        ),
        migrations.RemoveField(
            model_name="employment",
            name="work_days_override",
        ),
    ]
